# Generated by Django 5.1.4 on 2024-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets_bah", "0002_panier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="cle_billet",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
