# Generated by Django 5.0.7 on 2025-02-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_bah', '0005_utilisateur_clef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='clef',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='cle_utilisateur',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
