# Generated by Django 5.0.7 on 2025-02-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_bah', '0006_remove_utilisateur_clef_utilisateur_cle_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='cle_utilisateur',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
