# Generated by Django 5.0.7 on 2025-02-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_bah', '0009_utilisateurpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurpayment',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='utilisateurpayment',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='utilisateurpayment',
            name='stripe_product_id',
        ),
        migrations.AddField(
            model_name='utilisateurpayment',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurpayment',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurpayment',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
