# Generated by Django 5.0.7 on 2025-02-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_bah', '0010_remove_utilisateurpayment_product_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UtilisateurPayment',
        ),
    ]
