# Generated by Django 5.0.7 on 2025-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_bah', '0013_utilisateurprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurprofile',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='stripe_customer_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
