# Generated by Django 5.0.7 on 2025-02-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_bah', '0003_alter_reservation_cle_billet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='default_role',
            field=models.CharField(choices=[('super-admin', 'super-admin'), ('user', 'user')], default='user', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_superuser',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
