# Generated by Django 5.0.7 on 2025-02-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_bah', '0004_utilisateur_createdat_utilisateur_default_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='clef',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
